sudo: required
services:
  - docker

before_install:
  - docker build -t futuroz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run futuroz/react-test npm test -- --coverage

after_success:
  - docker build  -t futuroz/multi-client ./client
  - docker build  -t futuroz/multi-nginx ./nginx
  - docker build  -t futuroz/multi-server ./server
  - docker build  -t futuroz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push futuroz/multi-nginx
  - docker push futuroz/multi-server
  - docker push futuroz/multi-worker
  - docker push futuroz/multi-client
