sudo: required
services:
  - docker

before_install:
  - docker build -t futuroz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run futuroz/react-test npm test -- --coverage

after_success:
  - docker build  -t futuroz/muti-client ./client
  - docker build  -t futuroz/muti-nginx ./nginx
  - docker build  -t futuroz/muti-server ./server
  - docker build  -t futuroz/muti-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push futuroz/muti-client
  - docker push futuroz/muti-nginx
  - docker push futuroz/muti-server
  - docker push futuroz/muti-worker

